### PR TITLE
Add derivedFrom to register maker (rust version only)

### PR DESCRIPTION
**Pull request by kossnikita**
#158

### CODE REVIEW

**Comment by burrbull** [comment]
If it works correctly, it makes sense to do similar for `make_peripheral`, `make_cluster` and `make_field`.

**Comment by kossnikita** [comment]
Derive a field does not result in derive an enum, but literally derive a field:

```yaml
TIMER0:
  CR:
    _modify:
      IDR:
        derivedFrom: RELOAD
```

Clears enums and add attribute to field.

```xml
            <field derivedFrom="RELOAD">
              <name>IDR</name>
              <description>Selects, if Reload Register number is incremented, decremented or not modified</description>
              <bitRange>[27:26]</bitRange>
              <access>read-write</access>
            </field>
```

As far as I know, no current patch does this. It also doesn't work correctly with svd2rust: it tries to duplicate enumerations in the same module.

**Comment by burrbull** [comment]
> It also doesn't work correctly with svd2rust: it tries to duplicate enumerations in the same module.

Yeah. This is the bug.
Could you open issue in svd2rust repo?

**Comment by kossnikita** [comment]
https://github.com/rust-embedded/svd2rust/issues/745

**Review by burrbull — APPROVED** [review]

**Pull request merged**
