### PR TITLE
add writeConstraint range validation

### PR DESCRIPTION
**Pull request by kossnikita**
fixes https://github.com/rust-embedded/svd/issues/232

### CODE REVIEW

**Comment by kossnikita** [comment]
Is it better to add validation to svd_encoder::encode?

**Comment by burrbull** [comment]
I'm not sure. Most of validation work during parsing (for example by `svd2rust` or `svdtools convert`).

Maybe just `svdtools validate` tool?

**Comment by kossnikita** [comment]
I think it would be wrong if `svdtools patch` produces an invalid file (even if the patch is invalid)

**Comment by kossnikita** [comment]
> Maybe just `svdtools validate` tool?

#153
It won't do the same?

**Pull request closed without merging**
